### ISSUE TITLE
Taking CL Arguments

### ISSUE THREAD

**Issue by pdoongarwal** [MayankPratap/show-down#11]
@npcoder2k14 @MayankPratap Currently we are taking commands and arguments by **input()** . Rather than creating are own CLI, we can use any of python features/libraries to take CL arguments.

[Click](http://click.pocoo.org/5/)
This python library caught me eye, we can look into it.

**Comment by MayankPratap** [comment]
I am looking into it..

**Comment by pdoongarwal** [comment]
refer #22
