### ISSUE TITLE
Make the script portable

### ISSUE THREAD

**Issue by crisron-zz** [MayankPratap/show-down#20]
Your shebang line reads `#!/usr/bin/python`. What if I have python installed at `#!/usr/local/bin/python` instead? See [this](http://unix.stackexchange.com/a/12749/55629)

**Comment by kartikayx** [comment]
@MayankPratap 
You should use shebang line as 
`#!/usr/bin/env python`
instead of hardcoded
`#!/usr/bin/python` 
It will ensure the script uses the version of python defined in your `PATH` variable

**Comment by npcoder2k14** [comment]
Thanks for the suggestion. We will try to fix this in the best way possible.

**Comment by MayankPratap** [comment]
Fixed.
