### ISSUE TITLE
List of improvements

### ISSUE THREAD

**Issue by pdoongarwal** [MayankPratap/show-down#22]
- [x] Speed. We are doing calculation while writing in the file, this will decrease the speed, we can use asynchronus call, (multiprocessing )
- [x] Not flushing the data chunk
- [x] Argparser
- [x] Downloader section of code is poor in terms of redability
- [x] Relablling of `test.py`

Ping @npcoder2k14 @MayankPratap @shark-S

**Comment by MayankPratap** [comment]
Working on it..we will learn many new things ...

**Comment by ashish1294** [comment]
BeautifulSoup is better, more efficient and easier to use. Especially if you plan to change it to complex sites later.

**Comment by pdoongarwal** [comment]
@ashish1294 Certainly bs4 is more easier to use, but we are trying to remove dependencies.
We do not want user to download a library.
Still we are not sure about switching to HTMLParser.

**Comment by ashish1294** [comment]
@pdoongarwal Any particular reason for removing dependencies ? It's a small library. Doesn't make much difference. But it is more robust and provides better parsing results.

Pre-mature optimisations is root of all evil. So unless there is a good reason to remove it, we should bother about it.

**Comment by ashish1294** [comment]
Also, I think it's a bad idea of club up all issues on a single thread. It's difficult to discuss on particular design decision. There is a reason why people use isse tracker. Keeping a single thread defeats that purpose in my opinion.

**Comment by pdoongarwal** [comment]
@ashish1294 I agree with you on dependency one.
Will take care about not combining issues from now on.
