### ISSUE TITLE
Change file and branch name.

### ISSUE THREAD

**Issue by ashish1294** [MayankPratap/show-down#28]
Test is not a good name for file.

change branch name to development.

**Comment by pdoongarwal** [comment]
@ashish1294 @MayankPratap @shark-S @npcoder2k14 Changed the branch name test->dev

**Comment by MayankPratap** [comment]
Changed file name from test.py to episode.py

**Comment by MayankPratap** [comment]
Changed file name from test.py to episode.py

**Comment by ashish1294** [comment]
@MayankPratap : You also have to change the ReadMe instructions from test.py to episode.py
