### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by pbaisla** [MayankPratap/show-down#4]
Any response I give to `Do you wanna download it (y or n)` causes it to crash.

```
##############################################################################
 SOFTWARE_NAME ver 1.0 
##############################################################################

>> download -m sherlock -latest
Sending request ... 
/usr/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
The file in latest available is : Sherlock - The Abominable Bride (TvShows4Mobile.Com).mp4
('>> Do you wanna download it (y or n):',)
 y
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    main()
  File "test.py", line 41, in main
    user.downloadLatest(options['m'] , "mp4" )
  File "/home/prashant/github/show-down/showDown.py", line 52, in downloadLatest
    response = input(" ")
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```

**Comment by MayankPratap** [comment]
@pbaisla   Hello sir ... I have added dependencies in README.md. Only one extra module BeautifulSoup4 is required to be installed on system. Please check that if it is installed and give  us response.

**Comment by sunil-sangwan** [comment]
sir  this warning
"BeautifulSoup([your markup])
to this:
 BeautifulSoup([your markup], "html.parser")"
one reason of it is you have installed anacondaon system ...  so it can be reason.....

**Comment by pbaisla** [comment]
I don't have anaconda installed so that isn't the reason. I think you should follow the suggestion in the warning. As the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) says,

> Explicit is better than implicit.

BTW pulling the latest changes has fixed the problem and it works fine with `python3` but now it doesn't work with `python2`.

```
$ python2 test.py                 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from showDown import showDown
  File "/home/prashant/github/show-down/showDown.py", line 55
    print (">> Do you wanna download it (y or n):",end=" ")
```

I guess it's because the `print` function isn't available in `python2`. Try importing it from `__future__`.

**Comment by npcoder2k14** [comment]
not working with python 2.7 .....

**Comment by pdoongarwal** [comment]
@npcoder2k14 Please ellaborate with the error message.

**Comment by sunil-sangwan** [comment]
as above mentioned    NameError: name 'y' is not defined
its because python2.7 input can't support but now it is fixed.

**Comment by pdoongarwal** [comment]
@shark-S @npcoder2k14 I checked it is showing a NameError
I am working on it, it will fixed in few minutes.
